Code/EnhanceCWE-master/EnhancedCWE/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
"""EnhancedCWE URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from user_profile.views import ProfileView

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include('frontpage.urls', namespace='frontpage'),name = "frontpage"),
    url(r'^profile/$', ProfileView.as_view(), name='user_profile'),
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^accounts/', include('register.urls')),
    url(r'^app/login/', 'register.views.login'),
    url(r'^app/logout/', 'register.views.logout'),
    url(r'^app/password_change/', 'register.views.password_change'),
    url(r'^app/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'api/v1/', include('rest_api.urls')),   # Add "v1" to indicate the version.
    url(r'^comments/', include('comments.urls')),
]

Code/EnhanceCWE-master/comments/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from fluent_comments import urls as fluent_urls
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^delete/(\d+)/$', views.delete, name='comments-delete'),
] + fluent_urls.urlpatterns

Code/EnhanceCWE-master/frontpage/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^get_cwes/$', views.get_cwes, name='get_cwes'),
    url(r'^post_vote/$', views.post_vote, name='post_vote'),
    url(r'^get_misusecases/$', views.get_misusecases, name='get_misusecases'),
    url(r'^get_usecases/$', views.get_usecases, name='get_usecases'),
    url(r'^create_issue_report/$', views.create_issue_report, name='create_issue_report'),
    url(r'^process_issue_report/$', views.process_issue_report, name='process_issue_report'),
    url(r'^process_contact_us/$', views.process_contact_us, name='process_contact_us'),
]

Code/EnhanceCWE-master/register/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r"^login/$", views.login, name="account_login"),
    url(r'^', include('allauth.urls')),
]

Code/EnhanceCWE-master/rest_api/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.conf.urls import url
from rest_api import views

urlpatterns = [
    url(r'^cwe/text_related$', views.CWERelatedList.as_view(), name="restapi_CWETextRelated"),
    url(r'^cwe/all$', views.CWEAllList.as_view(), name="restapi_CWEAll"),
    url(r'^cwe/search_str', views.CWESearchSingleString.as_view(), name="restapi_CWESearchSingleString"),
    url(r'^misuse_case/cwe_related$', views.MisuseCaseRelated.as_view(), name="restapi_MisuseCase_CWERelated"),
    url(r'^use_case/misuse_case_related$', views.UseCaseRelated.as_view(), name="restapi_UseCase_MisuseCaseRelated"),
    url(r'^custom_muo/save$', views.SaveCustomMUO.as_view(), name="restapi_CustomMUO_Create"),
]

Code/EnhanceCWE-master/base/models.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class BaseModel(models.Model):
    """
    This is a base abstract model that provides basic common features that are
    necessary to most models.
    Interested models should inherit from this class instead of models.Model
    """
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, null=True, related_name='+')
    modified_by = models.ForeignKey(User, null=True, related_name='+')
    active = models.BooleanField(default=True, db_index=True)

    class Meta:
        abstract = True

Code/EnhanceCWE-master/muo/models.py
# @OPENSOURCE_HEADER_START@
# MORE Tool
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.contrib.contenttypes.models import ContentType
from django.core import urlresolvers
from django.db import models, transaction
from django.conf import settings
from cwe.models import CWE
from base.models import BaseModel
from django.core.exceptions import ValidationError
from django.db.models.signals import post_delete, pre_delete, pre_save, post_save
from django.dispatch import receiver
from signals import *
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.models import  User
from rest_api.utils import rest_api
from simple_history.models import HistoricalRecords

STATUS = [('draft', 'Draft'),
          ('in_review', 'In Review'),
          ('approved', 'Approved'),
          ('rejected', 'Rejected')]

ISSUE_TYPES = [('incorrect', 'Incorrect Content'),
                ('spam', 'Spam'),
                ('duplicate', 'Duplicate')]

ISSUE_STATUS = [('open', 'Open'),
                 ('investigating', 'Investigating'),
                ('reopened','Re-opened'),
                 ('resolved', 'Resolved')]

MISUSE_CASE_TYPE_CHOICES = [('existing', 'Existing'), ('new', 'New')]

OSR_PATTERN_CHOICES = [('ubiquitous', 'Ubiquitous'),
                       ('event-driven', 'Event-Driven'),
                       ('unwanted behavior', 'Unwanted Behavior'),
                       ('state-driven', 'State-Driven')]


# Tags are not used for now
class Tag(BaseModel):
    name = models.CharField(max_length=32, unique=True)

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"
        default_permissions = ('add', 'change', 'delete', 'view')

    def __unicode__(self):
        return self.name


class MUOQuerySet(models.QuerySet):
    """
    Define custom methods for the MUO QuerySet
    """


    def approved(self):
        # Returns the queryset for all the approved MUO Containers
        if self.model == MUOContainer:
            return self.filter(status='approved', is_published=True)
        elif self.model == MisuseCase:
            return self.filter(muocontainer__status='approved', muocontainer__is_published=True)
        elif self.model == UseCase:
            return self.filter(muo_container__status='approved', muo_container__is_published=True)


    def rejected(self):
        # Returns the queryset for all the rejected MUO Containers
        if self.model == MUOContainer:
            return self.filter(status='rejected')
        elif self.model == MisuseCase:
            return self.filter(muocontainer__status='rejected')
        elif self.model == UseCase:
            return self.filter(muo_container__status='rejected')

    def draft(self):
        # Returns the queryset for all the draft MUO Containers
        if self.model == MUOContainer:
            return self.filter(status='draft')
        elif self.model == MisuseCase:
            return self.filter(muocontainer__status='draft')
        elif self.model == UseCase:
            return self.filter(muo_container__status='draft')

    def in_review(self):
        # Returns the queryset for all the in review MUO Containers
        if self.model == MUOContainer:
            return self.filter(status='in_review')
        elif self.model == MisuseCase:
            return self.filter(muocontainer__status='in_review')
        elif self.model == UseCase:
            return self.filter(muo_container__status='in_review')

    def custom(self):
        # Returns the queryset for all the custom MUO Containers
        if self.model == MUOContainer:
            return self.filter(is_custom=True)
        elif self.model == MisuseCase:
            return self.filter(muocontainer__is_custom=True)
        elif self.model == UseCase:
            return self.filter(muo_container__is_custom=True)

    def published(self):
        # Returns the queryset for all the published MUO Containers
        if self.model == MUOContainer:
            return self.filter(is_published=True)
        elif self.model == MisuseCase:
            return self.filter(muocontainer__is_published=True)
        elif self.model == UseCase:
            return self.filter(muo_container__is_published=True)

    def unpublished(self):
        # Returns the queryset for all the unpublished MUO Containers
        if self.model == MUOContainer:
            return self.filter(is_published=False)
        elif self.model == MisuseCase:
            return self.filter(muocontainer__is_published=False)
        elif self.model == UseCase:
            return self.filter(muo_container__is_published=False)

class MUOManager(models.Manager):
    """
    Define custom methods that can be called on the MUO Manager
    """

    def get_queryset(self):
        return MUOQuerySet(self.model, using=self._db)

    def approved(self):
        return self.get_queryset().approved()

    def draft(self):
        return self.get_queryset().draft()

    def rejected(self):
        return self.get_queryset().rejected()

    def in_review(self):
        return self.get_queryset().in_review()

    def custom(self):
        return self.get_queryset().custom()


class MisuseCase(BaseModel):
    cwes = models.ManyToManyField(CWE, related_name='misuse_cases')
    tags = models.ManyToManyField(Tag, blank=True)
    name = models.CharField(max_length=16, null=True, blank=True, db_index=True, default="/")
    misuse_case_description = models.TextField(null=True, blank=True, verbose_name="Brief Description")
    misuse_case_primary_actor = models.CharField(max_length=256, null=True, blank=True, verbose_name="Primary actor")
    misuse_case_secondary_actor = models.CharField(max_length=256, null=True, blank=True, verbose_name="Secondary actor")
    misuse_case_precondition = models.TextField(null=True, blank=True, verbose_name="Pre-condition")
    misuse_case_flow_of_events = models.TextField(null=True, blank=True, verbose_name="Flow of events")
    misuse_case_postcondition = models.TextField(null=True, blank=True, verbose_name="Post-condition")
    misuse_case_assumption = models.TextField(null=True, blank=True, verbose_name="Assumption")
    misuse_case_source = models.TextField(null=True, blank=True, verbose_name="Source")

    objects = MUOManager()  # Replace the default manager with the MUOManager

    class Meta:
        verbose_name = "Misuse Case"
        verbose_name_plural = "Misuse Cases"

    def __unicode__(self):
        return "%s - %s..." % (self.name, self.misuse_case_description[:70])


@receiver(post_save, sender=MisuseCase, dispatch_uid='misusecase_post_save_signal')
def post_save_misusecase(sender, instance, created, using, **kwargs):
    """ Set the value of the field 'name' after creating the object """
    if created:
        instance.name = "MU-{0:05d}".format(instance.id)
        instance.save()


class MUOContainer(BaseModel):
    name = models.CharField(max_length=16, null=True, blank=True, db_index=True, default="/")
    cwes = models.ManyToManyField(CWE, related_name='muo_container')
    history = HistoricalRecords()

    misuse_case_type = models.CharField(max_length=16,
                                        null=True,
                                        blank=False,
                                        choices=MISUSE_CASE_TYPE_CHOICES,
                                        default='new',
                                        verbose_name='Misuse Case Type')

    misuse_case = models.ForeignKey(MisuseCase, on_delete=models.PROTECT, null=True, blank=True)

    misuse_case_name = models.CharField(max_length=16, null=True, blank=True, db_index=True, default="/")
    misuse_case_description = models.TextField(null=True, blank=True, verbose_name="Brief Description")
    misuse_case_primary_actor = models.CharField(max_length=256, null=True, blank=True, verbose_name="Primary actor")
    misuse_case_secondary_actor = models.CharField(max_length=256, null=True, blank=True, verbose_name="Secondary actor")
    misuse_case_precondition = models.TextField(null=True, blank=True, verbose_name="Pre-condition")
    misuse_case_flow_of_events = models.TextField(null=True, blank=True, verbose_name="Flow of events")
    misuse_case_postcondition = models.TextField(null=True, blank=True, verbose_name="Post-condition")
    misuse_case_assumption = models.TextField(null=True, blank=True, verbose_name="Assumption")
    misuse_case_source = models.TextField(null=True, blank=True, verbose_name="Source")

    reject_reason = models.TextField(null=True, blank=True)
    reviewed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True)
    status = models.CharField(choices=STATUS, max_length=64, default='draft')
    is_custom = models.BooleanField(default=False, db_index=True)
    is_published = models.BooleanField(default=False, db_index=True)
    rid = models.CharField(max_length=256,null=True, blank=True)
    objects = MUOManager()  # Replace the default manager with the MUOManager

    class Meta:
        verbose_name = "MUO Container"
        verbose_name_plural = "MUO Containers"
        # additional permissions
        permissions = (
            ('can_approve', 'Can approve MUO container'),
            ('can_reject', 'Can reject MUO container'),
            ('can_edit_all', 'Can edit all MUO Containers'),
            ('can_view_all', 'Can view all MUO containers'),
        )

    @staticmethod

Code/EnhanceCWE-master/frontpage/templates/frontpage/base.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% load account %}

{# Allow indexing by search engine robots#}
{% block blockbots %}{% endblock %}


{% block extra_header_menu %}
    {% block login_register_options %}
        {% if not user.is_authenticated %}
            <li><a href="{% url 'account_login' %}">{% trans 'Log in' %}</a></li>
            <li><a href="{% url 'account_signup' %}">{% trans 'Register' %}</a></li>
        {% endif %}
    {% endblock %}
{% endblock %}


{% block navbar %}
    <section class="content-header">
        {% block content_title %} {% endblock %}
    </section>
{% endblock %}

Code/EnhanceCWE-master/frontpage/templates/frontpage/create_issue_report.html
{% load i18n widget_tweaks  %}

<div class="modal-dialog report-issue-container">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                    aria-hidden="true">×</span></button>
            <h4 class="modal-title">Report {{ usecase.name }}</h4>
        </div>
        <form class="form-horizontal" enctype="multipart/form-data" action="{% url 'frontpage:process_issue_report' %}" method="post" novalidate>
            <div class="modal-body">
                {% csrf_token %}
                <input id="id_usecase" name="usecase" value="{{ usecase.id }}" hidden="hidden"/>

                <div class="form-group ">
                    <div class="control-label col-md-3">
                        {{ form.type.label_tag }}
                    </div>
                    <div class="controls col-md-12">
                        {{ form.type|add_class:"form-control"  }}
                    </div>

                    <div id="duplicate-container" style="display: none">
                        <div class="control-label col-md-6">
                            {{ form.usecase_duplicate.label_tag }}
                        </div>
                        <div class="controls col-md-12">
                            {{ form.usecase_duplicate|add_class:"form-control"  }}
                        </div>
                    </div>

                    <div class="control-label col-md-6">
                        {{ form.description.label_tag }}
                    </div>
                    <div class="controls col-md-12">
                        {{ form.description|add_class:"form-control"|attr:"rows:3"|attr:"placeholder:Enter issue description..." }}
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <input type="submit" id="report_button" class="btn btn-danger" value="{% trans 'Report' %}"
                       name="_report" disabled="disabled" />
            </div>
        </form>
    </div>
</div>

<script type="application/javascript">
    jQuery(function() {
        var container = $(".report-issue-container");
        var type = container.find('#id_type');
        var submit_button = container.find('#report_button');
        var duplicate_usecase = container.find('#id_usecase_duplicate');
        var duplicate_usecase_container = container.find('#duplicate-container');

        {# Handle disabling the submit button based on type choice and hiding/showing the duplicate use case selection #}
        type.on('change', function(e){
            if (type.val()) {
                submit_button.prop("disabled",false);
            } else {
                submit_button.prop("disabled",true);
            }

            if (type.val() == 'duplicate') {
                duplicate_usecase_container.show();
                if (duplicate_usecase.val() == null){
                    submit_button.prop("disabled",true);
                } else {
                    submit_button.prop("disabled",false);
                }

            } else {
                duplicate_usecase_container.hide();
            }
        });

        {# Handle disabiling the submit button based on value of usecase duplicate #}
        duplicate_usecase.on('change', function(e){

            if (duplicate_usecase.val() != null ) {
                if (type.val()) {
                    submit_button.prop("disabled",false);
                } else {
                    submit_button.prop("disabled",true);
                }
            } else {
                if (type.val() && type.val() != 'duplicate') {
                    submit_button.prop("disabled",false);
                } else {
                    submit_button.prop("disabled",true);
                }
            }
        });
    });

</script>

Code/EnhanceCWE-master/frontpage/templates/frontpage/index.html
{% extends "frontpage/base.html" %}
{% load i18n static crispy_forms_tags widget_tweaks %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'dist/css/select2.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'frontpage/frontpage.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'fluent_comments/css/ajaxcomments.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'comments/comments.css' %}" />
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <script src={% static "dist/js/select2.min.js" %}></script>
    <script src={% static "frontpage/frontpage.js" %}></script>
    <script type="text/javascript" src="{% static 'comments/comments.js' %}"></script>
{% endblock %}

{% block navbar %} {% endblock %}

{% block pre_container %}
    <div class="marquee" id="marquee" role="main" tabindex="-1">
        <div class="container">
            <span class="more-icon more-icon-lg more-icon-outline">
                MORE
            </span>

            <h2><b>M</b>alware-driven <b>O</b>verlooked <b>RE</b>quirements</h2>

            <p class="lead"> This site is meant to guide requirement engineers in identifying security requirements
                appropriate for their project. The site focuses on exploited vulnerabilities resulting from design
                flaws. For each new publicly posted exploited vulnerability, contributors can identify and provide a
                misuse case, use case and the overlooked security requirement(s) that created the vulnerability. This
                helps requirements engineers avoid these and potentially other vulnerabilities in their systems. Please
                register to use and enjoy.</p>

            {% if not user.is_authenticated %}
                <p class="lead">
                    <a href="{% url 'account_signup' %}" class="btn btn-outline-inverse btn-lg">Register Now</a>
                </p>
            {% endif %}

        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="col-md-12">

        <form class="form-horizontal" action method="post" novalidate>
            {% csrf_token %}

            <div class="col-md-12">
                <!-- <div id="div_id_cwes" class=" {% if form.cwes.errors %} has-error {% endif %}"> -->
                <!--     <label for="div_id_cwes" class="control-label  requiredField"> -->
                <!--         {{ form.cwes.label }} -->
                <!--     </label> -->

                <div class="input-group input-group-lg">
                          <select id="id_cwes" name="cwes" multiple="multiple"
                              style="width:100%;height:100%"
                              data-ajax-url="{% url 'frontpage:get_cwes' %}"
                              data-page-limit="{{ cwe_limit }}"></select>


                        <div class="input-group-btn">
                            <button class="btn btn-success btn-flat" id="cwe-submit-button" type="button"
                                    data-ajax-url="{% url 'frontpage:get_misusecases' %}"
                                    title="Misuse Cases, Use Cases &<br/>Overlooked Security Requirements"
                                    data-html="true">Get MUOs
                            </button>
                        </div>
                        <!-- /btn-group -->
                    </div>


                <!--     {% if form.cwes.errors %} -->
                <!--         {% for error in form.cwes.errors %} -->
                <!--             <p class="help-block"><strong>{{ error|escape }}</strong></p> -->
                <!--         {% endfor %} -->
                <!--     {% endif %} -->
                <!-- </div> -->
            </div>

            <div class="col-md-12 muo-search-container" style="display: none;">
                <div class="box box-primary">
                    <div class="box-body">
                        <div>
                            <div id="misuse-case-title-label">Misuse Cases</div>
                            <div id="use-case-title-label">Use Cases & Overlooked Security Requirements</div>
                        </div>
                        <hr style="margin: 0px;"/>
                        <div class="slim-scroll-div"></div>
                        {# slim-scroll-div is to loaded from misusecase.html after the ajax response #}
                        <div class="fat-scroll-div"></div>
                        {# fat-scroll-div is to loaded from usecase.html after the ajax response #}
                    </div>
                </div>
            </div>

            {# Modal used for popups, such as report inappropriate#}
            <div class="modal fade" id="muo-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true"></div>


        </form>

{% endblock %}