Code/ReportWriter-master/ReportWriter/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
"""ReportWriter URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from user_profile.views import ProfileView

urlpatterns = [
    url(r'^', include('frontpage.urls', namespace='frontpage')),
    url(r'^report/', include('report.urls', namespace='report')),
    url(r'^profile/$', ProfileView.as_view(), name='user_profile'),
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^accounts/', include('register.urls')),
    url(r'^app/login/', 'register.views.login'),
    url(r'^app/logout/', 'register.views.logout'),
    url(r'^app/password_change/', 'register.views.password_change'),
    url(r'^app/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^api/v1/', include('rest_api.urls')),

]

Code/ReportWriter-master/frontpage/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^process_contact_us/$', views.process_contact_us, name='process_contact_us'),
]

Code/ReportWriter-master/register/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r"^login/$", views.login, name="account_login"),
    url(r'^', include('allauth.urls')),
]

Code/ReportWriter-master/report/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.report_details, name='report_details'),
    url(r'^report_list/$', views.report_list, name='report_list'),
    url(r'^create_issue_report/$', views.create_issue_report, name='create_issue_report'),
    url(r'^process_issue_report/$', views.process_issue_report, name='process_issue_report'),

]

Code/ReportWriter-master/base/models.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class BaseModel(models.Model):
    """
    This is a base abstract model that provides basic common features that are
    necessary to most models.
    Interested models should inherit from this class instead of models.Model
    """
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, null=True, related_name='+')
    modified_by = models.ForeignKey(User, null=True, related_name='+')
    active = models.BooleanField(default=True, db_index=True)

    class Meta:
        abstract = True

Code/ReportWriter-master/frontpage/views.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.shortcuts import render
from mailer.util import send_email
from django.conf import settings
from django.contrib.auth.models import User
from django.template import Context
from django.http import Http404, JsonResponse

# Home screen
def index(request):
    return render(request, 'frontpage/index.html')

def process_contact_us(request):
    if request.method == 'POST':

        subject = request.POST['subject']
        content = request.POST['content']

        if not subject:
            raise Http404("Subject cannot be empty!\n")

        if not request.POST['user_name']:
            sender_name = "anonymous"
        else:
            sender_name = request.POST['user_name']

        message = "sender's name: "+request.POST['user_name']+"\n"

        if request.POST['user_email']:
            message += "sender's email: "+request.POST['user_email']+"\n"

        message += "subject: "+subject+"\n"
        message += "content: "+content+"\n"

        superuser = User.objects.get(is_superuser = True)
        
        send_email(subject=subject, users = [superuser], message=message,
            context=Context({'username': superuser.username, 'body': message}))

        return JsonResponse({'succ':True})
    else:
        raise Http404("Service not Available\n")

Code/ReportWriter-master/frontpage/templates/frontpage/base.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% load account %}

{# Allow indexing by search engine robots#}
{% block blockbots %}{% endblock %}


{% block extra_header_menu %}
    {% block login_register_options %}
        {% if not user.is_authenticated %}
            <li><a href="{% url 'account_login' %}">{% trans 'Log in' %}</a></li>
            <li><a href="{% url 'account_signup' %}">{% trans 'Register' %}</a></li>
        {% endif %}
    {% endblock %}
{% endblock %}


{% block navbar %}
    <section class="content-header">
        {% block content_title %} {% endblock %}
    </section>
{% endblock %}

Code/ReportWriter-master/frontpage/templates/frontpage/index.html
{% extends "frontpage/base.html" %}
{% load i18n static %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'frontpage/frontpage.css' %}"/>
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <script src={% static "frontpage/frontpage.js" %}></script>
{% endblock %}

{% block navbar %} {% endblock %}

{% block pre_container %}
    <div class="marquee" id="marquee" role="main" tabindex="-1">
        <div class="container">
            <span class="more-icon more-icon-lg more-icon-outline">
                MORE
            </span>

            <h2><b>M</b>alware-driven <b>O</b>verlooked <b>RE</b>quirements</h2>

            <p class="lead"> This site is meant to guide requirement engineers in identifying security requirements
                appropriate for their project. The site focuses on exploited vulnerabilities resulting from design
                flaws. For each new publicly posted exploited vulnerability, contributors can identify and provide a
                misuse case, use case and the overlooked security requirement(s) that created the vulnerability. This
                helps requirements engineers avoid these and potentially other vulnerabilities in their systems. Please
                register to use and enjoy.</p>

            {% if not user.is_authenticated %}
                <p class="lead">
                    <a href="{% url 'account_signup' %}" class="btn btn-outline-inverse btn-lg">Register Now</a>
                </p>
            {% endif %}

        </div>
    </div>
{% endblock %}


{% block content %}
    <div class="col-md-12">

        <form class="form-horizontal" action method="post" id="search-reports-form" novalidate
              data-ajax-url="{% url 'report:report_list' %}">
            {% csrf_token %}

            <div class="col-md-12">

                    <div class="input-group input-group-lg">

                        <input type="text" class="form-control" id="search-reports-input" name="search_reports" placeholder="Search Reports...">

                        <div class="input-group-btn">
                            <button class="btn btn-success btn-flat" id="search-reports-submit" type="submit">Search
                            </button>
                        </div>
                    </div>

            </div>

            <div class="col-md-12 search-reports-container" style="display: none;">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="search-reports-result">

                        </div>
                    </div>
                </div>
            </div>

            {# Modal used for popups, such as report inappropriate#}
            <div class="modal fade" id="report-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true"></div>


        </form>

{% endblock %}