Code/ReportWriter-master/ReportWriter/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
"""ReportWriter URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from user_profile.views import ProfileView

urlpatterns = [
    url(r'^', include('frontpage.urls', namespace='frontpage')),
    url(r'^report/', include('report.urls', namespace='report')),
    url(r'^profile/$', ProfileView.as_view(), name='user_profile'),
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^accounts/', include('register.urls')),
    url(r'^app/login/', 'register.views.login'),
    url(r'^app/logout/', 'register.views.logout'),
    url(r'^app/password_change/', 'register.views.password_change'),
    url(r'^app/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^api/v1/', include('rest_api.urls')),

]

Code/ReportWriter-master/register/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r"^login/$", views.login, name="account_login"),
    url(r'^', include('allauth.urls')),
]

Code/ReportWriter-master/report/urls.py
# @OPENSOURCE_HEADER_START@
# MORE Tool 
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.report_details, name='report_details'),
    url(r'^report_list/$', views.report_list, name='report_list'),
    url(r'^create_issue_report/$', views.create_issue_report, name='create_issue_report'),
    url(r'^process_issue_report/$', views.process_issue_report, name='process_issue_report'),

]

Code/ReportWriter-master/report/views.py
# @OPENSOURCE_HEADER_START@
# MORE Tool
# Copyright 2016 Carnegie Mellon University.
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED "AS IS," WITH NO WARRANTIES WHATSOEVER.
# CARNEGIE MELLON UNIVERSITY EXPRESSLY DISCLAIMS TO THE FULLEST EXTENT
# PERMITTEDBY LAW ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES,
# INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY
# RIGHTS.
#
# Released under a modified BSD license, please see license.txt for full
# terms. DM-0003473
# @OPENSOURCE_HEADER_END@
import autocomplete_light
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseForbidden, Http404, HttpResponseRedirect
from django.db.models import Q
import operator
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.utils.safestring import mark_safe
from report.models import Report, IssueReport
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse


def report_list(request):
    """
    This view is called by reports search using ajax to get the list of reports for a given search query
    """
    if not request.is_ajax():
        return HttpResponseForbidden()

    term = request.POST.get('term')
    query = []

    if term:
        if term.isdigit():
            query.append(Q(pk__exact=term))
            query.append(Q(cwes__code__exact=term))

        query.append(Q(name__icontains=term))
        query.append(Q(title__icontains=term))
        query.append(Q(description__icontains=term))
        query.append(Q(cwes__name__icontains=term))

        reports = Report.objects.approved().filter(reduce(operator.or_, query)).distinct()
    else:
        reports = Report.objects.approved()

    result_per_page = 5
    paginator = Paginator(reports, result_per_page)
    page = request.POST.get('page')

    try:
        cur_reports = paginator.page(page)
    except PageNotAnInteger:
        cur_reports = paginator.page(2)
    except EmptyPage:
        cur_reports = paginator.page(paginator.num_pages)

    context = {'reports': cur_reports, 'has_next': cur_reports.has_next()}

    page = render_to_string("report/report_list.html", context)
    return JsonResponse({'hasnext': cur_reports.has_next(), 'html': page})


def report_details(request, pk):
    report = Report.objects.get(pk=pk, status='approved')
    if not report:
        return Http404()

    context = {'report': report}
    return TemplateResponse(request, "report/report_details.html", context)



def create_issue_report(request):
    """
    This view is called by muo search using ajax to display the report issue popup
    """
    if request.method == "POST":
        # read the report_id that triggered this action
        report_id = request.POST.get('report_id')
        report = get_object_or_404(Report, pk=report_id)

        # Render issue report form and default initial values, if any
        ModelForm = autocomplete_light.modelform_factory(IssueReport, fields=('report', 'report_duplicate', 'description', 'type'))
        form = ModelForm()

        context = dict(
            form=form,
            report=report,
        )
        return TemplateResponse(request, "report/create_issue_report.html", context)
    else:
        raise Http404("Invalid access using GET request!")


def process_issue_report(request):
    """
    Handle adding new report created using muo search popup
    """
    if request.method == 'POST':

        ModelForm = autocomplete_light.modelform_factory(IssueReport, fields=('report', 'report_duplicate', 'description', 'type'))
        form = ModelForm(request.POST, request.FILES)
        if form.is_valid():
            new_object = form.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Issue Report %s has been created will be reviewed by our reviewers" % new_object.name)
        else:
            # submitted form is invalid
            errors = ["%s: %s" % (form.fields[field].label, error[0]) for field, error in form.errors.iteritems()]
            errors = '<br/>'.join(errors)
            messages.add_message(request, messages.ERROR, mark_safe("Invalid report content!<br/>%s" % errors) )

        return HttpResponseRedirect(reverse('report:report_details', kwargs={'pk': request.POST.get('report')}))

    else:
        raise Http404("Invalid access using GET request!")

Code/ReportWriter-master/report/templates/report/create_issue_report.html
{% load i18n widget_tweaks  %}

<div class="modal-dialog report-issue-container">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                    aria-hidden="true">×</span></button>
            <h4 class="modal-title">Report {{ usecase.name }}</h4>
        </div>
        <form class="form-horizontal" enctype="multipart/form-data" action="{% url 'report:process_issue_report' %}" method="post" novalidate>
            <div class="modal-body">
                {% csrf_token %}
                <input id="id_report" name="report" value="{{ report.id }}" hidden="hidden"/>

                <div class="form-group ">
                    <div class="control-label col-md-3">
                        {{ form.type.label_tag }}
                    </div>
                    <div class="controls col-md-12">
                        {{ form.type|add_class:"form-control"  }}
                    </div>

                    <div id="duplicate-container" style="display: none">
                        <div class="control-label col-md-6">
                            {{ form.report_duplicate.label_tag }}
                        </div>
                        <div class="controls col-md-12">
                            {{ form.report_duplicate|add_class:"form-control"  }}
                        </div>
                    </div>

                    <div class="control-label col-md-6">
                        {{ form.description.label_tag }}
                    </div>
                    <div class="controls col-md-12">
                        {{ form.description|add_class:"form-control"|attr:"rows:3"|attr:"placeholder:Enter issue description..." }}
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <input type="submit" id="report_button" class="btn btn-danger" value="{% trans 'Report' %}"
                       name="_report" disabled="disabled" />
            </div>
        </form>
    </div>
</div>

<script type="application/javascript">
    jQuery(function() {
        var container = $(".report-issue-container");
        var type = container.find('#id_type');
        var submit_button = container.find('#report_button');
        var duplicate_report = container.find('#id_report_duplicate');
        var duplicate_report_container = container.find('#duplicate-container');

        {# Handle disabling the submit button based on type choice and hiding/showing the duplicate use case selection #}
        type.on('change', function(e){
            if (type.val()) {
                submit_button.prop("disabled",false);
            } else {
                submit_button.prop("disabled",true);
            }

            if (type.val() == 'duplicate') {
                duplicate_report_container.show();
                if (duplicate_report.val() == null){
                    submit_button.prop("disabled",true);
                } else {
                    submit_button.prop("disabled",false);
                }

            } else {
                duplicate_report_container.hide();
            }
        });

        {# Handle disabiling the submit button based on value of report duplicate #}
        duplicate_report.on('change', function(e){

            if (duplicate_report.val() != null ) {
                if (type.val()) {
                    submit_button.prop("disabled",false);
                } else {
                    submit_button.prop("disabled",true);
                }
            } else {
                if (type.val() && type.val() != 'duplicate') {
                    submit_button.prop("disabled",false);
                } else {
                    submit_button.prop("disabled",true);
                }
            }
        });
    });

</script>

Code/ReportWriter-master/report/templates/report/report_details.html
{% extends "frontpage/base.html" %}
{% load i18n static %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'frontpage/frontpage.css' %}"/>
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <script src={% static "frontpage/frontpage.js" %}></script>
{% endblock %}


{% block title %}{{ report.title }}{% endblock %}


{% block content %}

    {{ block.super }}

    <div class="box box-primary report-details">
        <div class="box-header with-border">
            <div class="col-md-10">
                <h3 class="box-title"><b>{{ report.name}}: {{ report.title }}</b></h3>
            </div>
            <div class="col-md-2">
                {{ report.created_at }}
            </div>

        </div>

        <div class="box-body">
            <div class="col-md-12">
                <div class="col-md-12">
                    <p>
                        {{ report.description }}
                    </p>
                </div>

                <div class="col-md-12" style="margin-top:10px;">
                    {% for cwe in report.cwes.all %}
                        <span class="label cwe-label">{{ cwe }}</span>
                    {% endfor %}

                    <hr style="border: none; margin: 30px 0"/>

                </div>


                <div class="col-md-6" style="margin-top:15px;">
                    <b>Misuse Case</b>
                    <hr style="margin-top:0"/>

                    {% if report.misuse_case_description %}
                        <label class="light-label">Description</label>
                        {{ report.misuse_case_description|linebreaks }}
                    {% endif %}

                    {% if report.misuse_case_primary_actor %}
                        <label class="light-label">Primary Actor</label>
                        {{ report.misuse_case_primary_actor|linebreaks }}
                    {% endif %}

                    {% if report.misuse_case_secondary_actor %}
                        <label class="light-label">Secondary Actor</label>
                        {{ report.misuse_case_secondary_actor|linebreaks }}
                    {% endif %}

                    {% if report.misuse_case_precondition %}
                        <label class="light-label">Pre-condition</label>
                        {{ report.misuse_case_precondition|linebreaks }}
                    {% endif %}

                    {% if report.misuse_case_flow_of_events %}
                        <label class="light-label">Flow of events</label>
                        {{ report.misuse_case_flow_of_events|linebreaks }}
                    {% endif %}

                    {% if report.misuse_case_assumption %}
                        <label class="light-label">Assumption</label>
                        {{ report.misuse_case_assumption|linebreaks }}
                    {% endif %}

                    {% if report.misuse_case_source %}
                        <label class="light-label">Source</label>
                        {{ report.misuse_case_source|linebreaks }}
                    {% endif %}
                </div>


                <div class="col-md-6" style="margin-top:15px;">
                    <b>Use Case</b>
                    <hr style="margin-top:0"/>

                    {% if report.use_case_description %}
                        <label class="light-label">Description</label>
                        {{ report.use_case_description|linebreaks }}
                    {% endif %}

                    {% if report.use_case_primary_actor %}
                        <label class="light-label">Primary Actor</label>
                        {{ report.use_case_primary_actor|linebreaks }}
                    {% endif %}

                    {% if report.use_case_secondary_actor %}
                        <label class="light-label">Secondary Actor</label>
                        {{ report.use_case_secondary_actor|linebreaks }}
                    {% endif %}

                    {% if report.use_case_precondition %}
                        <label class="light-label">Pre-condition</label>
                        {{ report.use_case_precondition|linebreaks }}
                    {% endif %}

                    {% if report.use_case_flow_of_events %}
                        <label class="light-label">Flow of events</label>
                        {{ report.use_case_flow_of_events|linebreaks }}
                    {% endif %}

                    {% if report.use_case_assumption %}
                        <label class="light-label">Assumption</label>
                        {{ report.use_case_assumption|linebreaks }}
                    {% endif %}

                    {% if report.use_case_source %}
                        <label class="light-label">Source</label>
                        {{ report.use_case_source|linebreaks }}
                    {% endif %}
                </div>


                <div class="col-md-12" style="margin-top:30px">
                    <b>Overlooked Security Requirement</b>
                    <hr style="margin-top:0"/>
                    {{ report.osr|linebreaks }}
                </div>

                {% if user.is_authenticated %}
                <div class="pull-right">
                    <a href="#report-modal" class="btn btn-xs" data-toggle="modal"
                       data-ajax-url="{% url 'report:create_issue_report' %}"
                       data-report-id="{{ report.pk }}"
                       title data-original-title="Report Issue">
                        <span class="fa fa-exclamation-triangle"></span>
                        Report Issue
                    </a>
                </div>
                {% endif %}

            </div>
        </div>
    </div>

    {# Modal used for popups, such as report inappropriate#}
    <div class="modal fade" id="report-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true"></div>


    <script>
    jQuery(function() {

        $("#report-modal").on("show.bs.modal", function (e) {
            var report_id = $(e.relatedTarget).data('report-id');
            var url = $(e.relatedTarget).data('ajax-url');

            // Load the report issue dialog
            $.ajax({
                url: url,
                type: 'POST',
                data: {report_id: report_id}, // Send the selected use case id

                success: function (result) {
                    $(e.currentTarget).html(result);
                },

                error: function (xhr, errmsg, err) {
                    // Show error message in the alert
                    alert("Oops! We have encountered and error \n" + errmsg);
                }
            });
        });
    });
    </script>

{% endblock %}

Code/ReportWriter-master/report/templates/report/report_list.html
{% load static %}

{% if reports %}
    <table class="table table-hover ">
        <tbody>
        {% for report in reports %}
            <tr>
                <td {% if forloop.first %} style="border-top:none" {% endif %}>
                    <span class="report-title">{{ report.title }}</span>
                    <span class="report-date">{{ report.created_at }}</span>
                    <div class="report-desc">{{ report.description|linebreaks|truncatewords:100 }}</div>
                    <div class="report-readmore"><a href="{% url 'report:report_details' report.pk %}">Read more...</a></div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% else %}
    <p>Sorry, no reports found matching your query!</p>
{% endif %}